export const NORAMP_PRICE_ID = process.env.NEXT_PUBLIC_NORAMP_PRICE_ID;

export const MINT_CONFIG = {
  TRIGGER_ID: process.env.NEXT_PUBLIC_NORAMP_MINT_TRIGGER_ID,
  APP_ID: process.env.NEXT_PUBLIC_NORAMP_MINT_APP_ID,
  COMPRESSED_MINT_TRIGGER_ID:
    process.env.NEXT_PUBLIC_NORAMP_COMPRESSED_MINT_TRIGGER_ID,
};

export const TRANSFER_CONFIG = {
  PRICE_ID: process.env.NEXT_PUBLIC_NORAMP_TRANSFER_PRICE_ID,
};

export const IS_MAINNET = process.env.NEXT_PUBLIC_IS_MAINNET === 'true';

export const COMPRESSED_CONFIG = {
  APP_ID: process.env.NEXT_PUBLIC_NORAMP_COMPRESSED_APP_ID,
  TRIGGER_ID: process.env.NEXT_PUBLIC_NORAMP_COMPRESSED_TRIGGER_ID,

  TREE_ADDRESS: process.env.NEXT_PUBLIC_NORAMP_COMPRESSED_TREE_ADDRESS,
  MINT_ADDRESS: process.env.NEXT_PUBLIC_NORAMP_COMPRESSED_MINT_ADDRESS,
  METADATA_ACCOUNT_ADDRESS:
    process.env.NEXT_PUBLIC_NORAMP_COMPRESSED_METADATA_ACCOUNT_ADDRESS,
  MASTER_EDITION_ACCOUNT_ADDRESS:
    process.env.NEXT_PUBLIC_NORAMP_COMPRESSED_MASTER_EDITION_ACCOUNT_ADDRESS,
};
